ALTER TABLE USERTABLE
    ADD COLUMN EMAIL VARCHAR(500) NOT NULL DEFAULT 'NA';

ALTER TABLE USERTABLE
    ADD COLUMN PHONE_NUMBER VARCHAR(10) NOT NULL DEFAULT 'NA';

ALTER TABLE USERTABLE
    ADD COLUMN AGE_GROUP INT NOT NULL DEFAULT 0;

ALTER TABLE USERTABLE
    ADD COLUMN ROLE VARCHAR(254) NOT NULL DEFAULT 'NA';

